-- =====================================================================
-- COOPR8 Stage 0 / V12 -- Tenant payment accounts and payment records.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   Two defects, both of which need a table that does not exist yet.
--
--   1. THE WEBHOOK HAS NO IDEMPOTENCY KEY. Nothing in V1-V11 stores a
--      payment provider's transaction reference. repay.txn_id,
--      saving.txn_id and shares.txn_id all hold a LOCALLY generated
--      TxnIdGen value ("yyyyMMddHHmm" + 3 random digits) with
--      channel = 'PAYSTACK' as the only marker that money came from a
--      gateway, and none of them is unique. So a webhook replayed by
--      Paystack -- which Paystack does, on its own retry schedule --
--      credited a member's savings twice, and there was no column
--      anywhere the database could have refused it on.
--
--   2. A PAYMENT HAD NO AUTHORITATIVE OWNER RECORD. The organization a
--      payment belonged to was recovered from metadata carried on the
--      transaction. That is a provider-side hint about a COOPR8 fact.
--      The fact now lives here, written before the provider is ever
--      called, so the webhook resolves the cooperative AND the member
--      from COOPR8's own row rather than from anything an external
--      caller can influence.
--
-- PROVIDER-NEUTRAL, PAYSTACK-FIRST
--   No column here is named after Paystack. "provider_account_reference"
--   holds what Paystack calls a subaccount code (ACCT_xxxxxxxx) when the
--   provider is PAYSTACK; a different provider's account handle fits the
--   same column. Paystack is the only provider with an implementation --
--   see PaymentProviderRegistry, which fails closed for a provider that
--   has no bean. Listing FLUTTERWAVE in the CHECK constraints does not
--   make it supported; it makes the constraint stable when it is.
--
-- NO TENANT PROVIDER CREDENTIALS ARE STORED
--   There is deliberately no secret_key column, and no encrypted-secret
--   column either. The platform's Paystack secret is a server-side
--   application secret (PAYSTACK_SECRET_KEY) and stays one. A tenant
--   configures a settlement destination, never an API credential.
--
-- NOTHING IS SEEDED
--   Unlike V9, this migration seeds no rows. A cooperative with no
--   payment configuration MUST fail closed -- absence is the correct
--   initial state, and seeding would mean inventing a settlement
--   destination for somebody else's money.
--
-- V1-V11 ARE NOT MODIFIED. Purely additive: two new tables, one index.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. organization_payment_config -- exactly one row per organization.
-- ---------------------------------------------------------------------
-- Where a cooperative's money is settled, and by which provider. The
-- constraints below are the point of the table: they make the security
-- rules facts the database enforces rather than promises the service
-- layer makes.
CREATE TABLE organization_payment_config (
    id                         bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id            bigint       NOT NULL,

    -- Which payment provider settles this cooperative's money.
    provider                   varchar(32)  NOT NULL,

    -- How the provider account is held. PLATFORM_SUBACCOUNT means the
    -- account sits under COOPR8's platform merchant account and the
    -- provider splits settlement to it. NONE means online payment is
    -- configured but has no destination yet, which is not payable.
    account_mode               varchar(32)  NOT NULL,

    -- The provider's handle for that account. Paystack: 'ACCT_xxxxxxxx'.
    -- NULL until the provider has actually issued one.
    provider_account_reference varchar(255),

    status                     varchar(32)  NOT NULL,

    -- The settlement destination the cooperative gave us, kept so that an
    -- interrupted setup can be RECONCILED against the provider rather
    -- than retried blindly into a second account. Not a credential.
    settlement_bank_code       varchar(32),
    settlement_account_number  varchar(32),
    settlement_account_name    varchar(255),

    created_at                 timestamp(6),
    updated_at                 timestamp(6),

    CONSTRAINT pk_organization_payment_config
        PRIMARY KEY (id),

    -- One payment configuration per cooperative. This is also what makes
    -- "claim the row first, then call the provider" a safe way to start
    -- an account setup: two concurrent setups cannot both claim.
    CONSTRAINT uk_organization_payment_config_organization
        UNIQUE (organization_id),

    CONSTRAINT fk_organization_payment_config_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),

    -- No two cooperatives may point at the same provider account. This is
    -- the database refusing, outright, to let one tenant's money be
    -- settled into another tenant's account -- including by an
    -- administrator who somehow reached past the service layer.
    -- (NULLs are distinct in PostgreSQL, so any number of rows may sit at
    -- NULL while their setup is still in flight.)
    CONSTRAINT uk_organization_payment_config_provider_account
        UNIQUE (provider, provider_account_reference),

    CONSTRAINT ck_organization_payment_config_provider
        CHECK (provider IN ('PAYSTACK', 'FLUTTERWAVE')),

    CONSTRAINT ck_organization_payment_config_account_mode
        CHECK (account_mode IN ('NONE', 'PLATFORM_SUBACCOUNT')),

    CONSTRAINT ck_organization_payment_config_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'DISABLED')),

    -- A cooperative cannot be marked connected without an account to be
    -- connected to. So a provider call that fails -- or times out before
    -- it answers -- cannot leave the tenant looking payable: there is no
    -- reference to store, therefore ACTIVE is not a state the row can
    -- reach. The failure mode is "still PENDING", which is reconcilable.
    CONSTRAINT ck_organization_payment_config_active_reference
        CHECK (status <> 'ACTIVE'
               OR account_mode = 'NONE'
               OR (provider_account_reference IS NOT NULL
                   AND length(btrim(provider_account_reference)) > 0)),

    -- A subaccount is settled somewhere. Recording where is what makes an
    -- interrupted setup reconcilable instead of ambiguous.
    CONSTRAINT ck_organization_payment_config_settlement
        CHECK (account_mode <> 'PLATFORM_SUBACCOUNT'
               OR (settlement_bank_code IS NOT NULL
                   AND settlement_account_number IS NOT NULL))
);


-- ---------------------------------------------------------------------
-- 2. payment_transaction -- one row per payment COOPR8 started.
-- ---------------------------------------------------------------------
-- Written BEFORE the provider is called, with a reference COOPR8 itself
-- generated, so that by the time any webhook can arrive the row it names
-- already exists. That ordering is what lets the webhook resolve the
-- tenant from COOPR8's own data.
CREATE TABLE payment_transaction (
    id                 bigint        GENERATED BY DEFAULT AS IDENTITY,
    organization_id    bigint        NOT NULL,
    user_id            bigint        NOT NULL,
    provider           varchar(32)   NOT NULL,

    -- The reference the provider knows this payment by. COOPR8 supplies
    -- it at initialization rather than adopting whatever the provider
    -- generates, so the row exists first and the two can never disagree.
    provider_reference varchar(255)  NOT NULL,

    -- What the money is for, and which loan when it is a repayment.
    purpose            varchar(32)   NOT NULL,
    target_id          bigint,

    amount             numeric(38,2) NOT NULL,

    -- PENDING until a verified provider event credits it. The move to
    -- SUCCEEDED is a conditional UPDATE ... WHERE status = 'PENDING' in
    -- the same transaction as the credit, so the claim and the money
    -- commit together or not at all.
    status             varchar(32)   NOT NULL,
    processed_at       timestamp(6),

    created_at         timestamp(6),
    updated_at         timestamp(6),

    CONSTRAINT pk_payment_transaction
        PRIMARY KEY (id),

    -- The idempotency backstop. A provider reference is processable at
    -- most once because it can only EXIST once: two concurrent
    -- initializations that somehow produced the same reference cannot
    -- both insert, and a replayed webhook has exactly one row to claim.
    CONSTRAINT uk_payment_transaction_provider_reference
        UNIQUE (provider, provider_reference),

    CONSTRAINT fk_payment_transaction_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),

    -- Composite, against uk_users_org_id from V8. The payer must belong to
    -- the cooperative being credited -- the database will not store a
    -- payment whose member is in one organization and whose money is in
    -- another, whatever the service layer believes.
    CONSTRAINT fk_payment_transaction_member
        FOREIGN KEY (organization_id, user_id)
            REFERENCES users (organization_id, id),

    CONSTRAINT ck_payment_transaction_provider
        CHECK (provider IN ('PAYSTACK', 'FLUTTERWAVE')),

    CONSTRAINT ck_payment_transaction_purpose
        CHECK (purpose IN ('SAVINGS', 'REPAYMENT', 'SHARES')),

    CONSTRAINT ck_payment_transaction_status
        CHECK (status IN ('PENDING', 'SUCCEEDED')),

    CONSTRAINT ck_payment_transaction_amount
        CHECK (amount > 0),

    -- A repayment names the loan it pays. Without this the webhook would
    -- have a purpose it could not act on.
    CONSTRAINT ck_payment_transaction_repayment_target
        CHECK (purpose <> 'REPAYMENT' OR target_id IS NOT NULL),

    -- Processed exactly when there is a processing time, so "has this
    -- been credited" has one answer rather than two that can disagree.
    CONSTRAINT ck_payment_transaction_processed_at
        CHECK ((status = 'SUCCEEDED') = (processed_at IS NOT NULL))
);


-- A cooperative reads its own payments; nobody reads all of them.
CREATE INDEX ix_payment_transaction_organization
    ON payment_transaction (organization_id);
