-- =====================================================================
-- COOPR8 Phase 1 / V15 -- Plans, platform admin, subscriptions & entitlements
-- =====================================================================

-- 1. Global plans catalogue
CREATE TABLE plans (
    id                   bigint       GENERATED BY DEFAULT AS IDENTITY,
    code                 varchar(64)  NOT NULL,
    name                 varchar(255) NOT NULL,
    price                numeric(12, 2) NOT NULL,
    currency             varchar(8)   NOT NULL DEFAULT 'NGN',
    billing_period       varchar(32)  NOT NULL DEFAULT 'ANNUAL',
    per_user_price       numeric(12, 2),
    included_users       integer,
    ai_scanning_enabled  boolean      NOT NULL DEFAULT false,
    ecommerce_enabled    boolean      NOT NULL DEFAULT false,
    active               boolean      NOT NULL DEFAULT true,
    sort_order           integer      NOT NULL DEFAULT 0,
    created_at           timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_plans PRIMARY KEY (id),
    CONSTRAINT uk_plans_code UNIQUE (code)
);

-- Seed initial plans (Enterprise inactive pending custom ecommerce module; Legacy hidden & active=false)
INSERT INTO plans (code, name, price, currency, billing_period, per_user_price, included_users, ai_scanning_enabled, ecommerce_enabled, active, sort_order)
VALUES
    ('BASIC', 'Basic', 150000.00, 'NGN', 'ANNUAL', NULL, NULL, false, false, true, 1),
    ('PROFESSIONAL', 'Professional / AI', 250000.00, 'NGN', 'ANNUAL', NULL, NULL, true, false, true, 2),
    ('ENTERPRISE', 'Enterprise / Complete', 350000.00, 'NGN', 'ANNUAL', NULL, NULL, true, true, false, 3),
    ('LEGACY', 'Legacy Complimentary', 0.00, 'NGN', 'ANNUAL', NULL, NULL, true, true, false, 99);

-- 2. Plan price audit log (append-only)
CREATE TABLE plan_price_audit (
    id                   bigint       GENERATED BY DEFAULT AS IDENTITY,
    plan_id              bigint       NOT NULL,
    old_price            numeric(12, 2) NOT NULL,
    new_price            numeric(12, 2) NOT NULL,
    old_per_user_price   numeric(12, 2),
    new_per_user_price   numeric(12, 2),
    changed_by           bigint       NOT NULL,
    changed_at           timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_plan_price_audit PRIMARY KEY (id),
    CONSTRAINT fk_plan_price_audit_plan FOREIGN KEY (plan_id) REFERENCES plans (id)
);

-- 3. Platform Super Admins (global)
CREATE TABLE platform_admins (
    id                   bigint       GENERATED BY DEFAULT AS IDENTITY,
    email                varchar(255) NOT NULL,
    password_hash        varchar(255) NOT NULL,
    status               varchar(32)  NOT NULL DEFAULT 'ACTIVE',
    created_at           timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_platform_admins PRIMARY KEY (id),
    CONSTRAINT uk_platform_admins_email UNIQUE (email)
);

-- 4. Organization subscriptions, entitlements and domains
ALTER TABLE organizations ADD COLUMN plan_code varchar(64);
ALTER TABLE organizations ADD COLUMN agreed_price numeric(12, 2);
ALTER TABLE organizations ADD COLUMN billing_period_snapshot varchar(32);
ALTER TABLE organizations ADD COLUMN per_user_price_snapshot numeric(12, 2);
ALTER TABLE organizations ADD COLUMN included_users_snapshot integer;
ALTER TABLE organizations ADD COLUMN ai_scanning_override boolean;
ALTER TABLE organizations ADD COLUMN ecommerce_override boolean;
ALTER TABLE organizations ADD COLUMN subscription_starts_at timestamp(6);
ALTER TABLE organizations ADD COLUMN subscription_ends_at timestamp(6);
ALTER TABLE organizations ADD COLUMN subdomain varchar(64);
ALTER TABLE organizations ADD COLUMN custom_domain varchar(255);
ALTER TABLE organizations ADD COLUMN custom_domain_verified boolean NOT NULL DEFAULT false;
ALTER TABLE organizations ADD COLUMN custom_domain_verification_token varchar(128);

ALTER TABLE organizations ADD CONSTRAINT fk_organizations_plan FOREIGN KEY (plan_code) REFERENCES plans (code);
ALTER TABLE organizations ADD CONSTRAINT uk_organizations_subdomain UNIQUE (subdomain);
ALTER TABLE organizations ADD CONSTRAINT uk_organizations_custom_domain UNIQUE (custom_domain);

-- 5. Widen organization status check constraint
ALTER TABLE organizations DROP CONSTRAINT ck_organizations_status;
ALTER TABLE organizations ADD CONSTRAINT ck_organizations_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', 'PENDING_ACTIVATION'));

-- 6. Backfill existing pre-Phase 1 organizations onto complimentary LEGACY plan with no expiry
UPDATE organizations
SET plan_code = 'LEGACY',
    agreed_price = 0,
    billing_period_snapshot = 'ANNUAL',
    subscription_starts_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    subscription_ends_at = NULL
WHERE plan_code IS NULL;

