-- =====================================================================
-- COOPR8 Phase 1 / V1 -- Initial COOPR8 schema (fresh / empty database).
-- =====================================================================
--
-- This is the SINGLE canonical migration that builds the entire COOPR8
-- schema from scratch on a brand-new, EMPTY PostgreSQL database. COOPR8 is
-- the multi-tenant SaaS operated by Invo Technologies; this schema is
-- provider-owned and product-generic. It does NOT assume, seed, or convert
-- any pre-existing "Citadel" data -- the historical Citadel database is a
-- separate, later, controlled IMPORT source, never the schema origin.
--
-- HOW THIS FILE WAS DERIVED (fidelity to the JPA mapping):
--   Column names and JDBC types were taken from the DDL that Hibernate 6.5
--   itself emits for the current @Entity classes (generated offline, with no
--   DB connection, via SchemaGenTest using the same Spring Boot 3.3.5 naming
--   strategies the running app uses: CamelCaseToUnderscoresNamingStrategy +
--   SpringImplicitNamingStrategy). Because the physical names/types match what
--   Hibernate expects, `spring.jpa.hibernate.ddl-auto=validate` passes at boot.
--   Notable exact names locked from that output: users.ledgerid,
--   loan.guarantor1status, loan.guarantor2status.
--
-- MULTI-TENANCY (shared DB, shared schema, tenant-per-row):
--   `organizations` is the tenant root. Every tenant-owned table carries a
--   NOT NULL organization_id FK to it, indexed, so every query is trivially
--   tenant-scopable and the Phase 2 Hibernate @Filter can be uniform. The OTP
--   table is intentionally NOT tenant-scoped in Phase 1 (email-keyed only).
--
-- ENUMS: persisted as STRING from the start (@Enumerated(EnumType.STRING)).
--   The columns are varchar with CHECK constraints mirroring Hibernate's own
--   generated DDL. NOTE (maintenance): adding a new enum constant later (most
--   likely to NotificationType) requires a migration to ALTER the matching
--   CHECK constraint, otherwise inserts of the new value fail even though
--   Hibernate `validate` -- which ignores CHECK constraints -- still passes.
--
-- WHAT WAS FOLDED IN / RETIRED (previous stepwise migrations, now removed):
--   V2 (create organizations)          -> folded into this file.
--   V3 (nullable org_id + indexes)     -> folded; org_id is NOT NULL from the start.
--   V5 (org_id NOT NULL + FK)          -> folded directly into CREATE TABLE.
--   V6 (per-tenant unique constraints) -> folded; ledger column confirmed = ledgerid.
--   V4 (seed Citadel + backfill)       -> RETIRED: must NOT seed a tenant on a
--                                          fresh provider DB; no rows to backfill.
--   V7 (enum ordinal -> string)        -> RETIRED: entities already map STRING, so
--                                          the columns are created as varchar directly.
--
-- Forward-only and additive. Nothing here drops, resets, or truncates data.

-- ---------------------------------------------------------------------
-- Tenant root
-- ---------------------------------------------------------------------
CREATE TABLE organizations (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    name            varchar(255) NOT NULL,
    legal_name      varchar(255),
    slug            varchar(255) NOT NULL,
    email           varchar(255),
    phone           varchar(255),
    address         varchar(255),
    website         varchar(255),
    logo_url        varchar(255),
    primary_color   varchar(255),
    secondary_color varchar(255),
    ledger_prefix   varchar(255) NOT NULL,
    status          varchar(32)  NOT NULL,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    CONSTRAINT pk_organizations       PRIMARY KEY (id),
    CONSTRAINT uk_organizations_slug  UNIQUE (slug),
    CONSTRAINT ck_organizations_status CHECK (status IN ('ACTIVE','SUSPENDED'))
);

-- ---------------------------------------------------------------------
-- Members / admins (tenant-owned)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id                       bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id          bigint       NOT NULL,
    ledgerid                 varchar(255),
    ledger_number            integer      NOT NULL,
    first_name               varchar(255),
    middle_name              varchar(255),
    last_name                varchar(255),
    email                    varchar(255),
    phone                    varchar(255),
    address                  varchar(255),
    psn                      varchar(255),
    occupation               varchar(255),
    ver_no                   varchar(255),
    station                  varchar(255),
    marital                  varchar(255),
    gender                   varchar(255),
    home_town                varchar(255),
    lga                      varchar(255),
    state                    varchar(255),
    passport                 varchar(255),
    password                 varchar(255),
    status                   varchar(255),
    role                     varchar(20),
    payment_type             varchar(20),
    next_of_kin              varchar(255),
    next_of_kin_relationship varchar(255),
    next_of_kin_address      varchar(255),
    next_of_kin_phone        varchar(255),
    savings_balance          numeric(38,2),
    loan_balance             numeric(38,2),
    shares_balance           numeric(38,2),
    total_purchase           numeric(38,2),
    saving_plan              numeric(38,2),
    special_saving_plan      numeric(38,2),
    share_plan               numeric(38,2),
    profit                   numeric(38,2),
    created_at               timestamp(6),
    modified_at              timestamp(6),
    CONSTRAINT pk_users               PRIMARY KEY (id),
    CONSTRAINT fk_users_organization  FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_users_role          CHECK (role IN ('ROLE_MEMBER','ROLE_ADMIN')),
    CONSTRAINT ck_users_payment_type  CHECK (payment_type IN ('GOVERNMENT','SELF_PAY'))
);

-- ---------------------------------------------------------------------
-- One-time passwords (NOT tenant-scoped in Phase 1; email-keyed)
-- ---------------------------------------------------------------------
CREATE TABLE otp (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY,
    email      varchar(255),
    otp        varchar(255),
    created_at timestamp(6),
    expired_at timestamp(6),
    CONSTRAINT pk_otp PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Loans (tenant-owned)
-- ---------------------------------------------------------------------
CREATE TABLE loan (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id   bigint       NOT NULL,
    user_id           bigint,
    guarantor1_id     bigint,
    guarantor2_id     bigint,
    amount            numeric(38,2),
    balance           numeric(38,2),
    repay_amount      numeric(38,2),
    duration          integer,
    installments_paid integer,
    start_date        date,
    end_date          date,
    account_details   varchar(255),
    guarantor1status  varchar(255),
    guarantor2status  varchar(255),
    purpose           varchar(255),
    remark            varchar(255),
    status            varchar(255),
    type              varchar(255),
    created_at        timestamp(6),
    modified_at       timestamp(6),
    CONSTRAINT pk_loan              PRIMARY KEY (id),
    CONSTRAINT fk_loan_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_loan_user         FOREIGN KEY (user_id)         REFERENCES users (id),
    CONSTRAINT fk_loan_guarantor1   FOREIGN KEY (guarantor1_id)   REFERENCES users (id),
    CONSTRAINT fk_loan_guarantor2   FOREIGN KEY (guarantor2_id)   REFERENCES users (id)
);

-- ---------------------------------------------------------------------
-- Loan repayments (tenant-owned). parent_loan_id is a plain reference
-- (matches the entity: not a mapped association -> no FK).
-- ---------------------------------------------------------------------
CREATE TABLE repay (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint       NOT NULL,
    user_id         bigint,
    loan_id         bigint,
    parent_loan_id  bigint,
    amount          numeric(38,2),
    balance         numeric(38,2),
    channel         varchar(255),
    loan_type       varchar(255),
    status          varchar(255),
    txn_id          varchar(255),
    created_at      timestamp(6),
    modified_at     timestamp(6),
    CONSTRAINT pk_repay              PRIMARY KEY (id),
    CONSTRAINT fk_repay_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_repay_user         FOREIGN KEY (user_id)         REFERENCES users (id),
    CONSTRAINT fk_repay_loan         FOREIGN KEY (loan_id)         REFERENCES loan (id)
);

-- ---------------------------------------------------------------------
-- Savings (tenant-owned)
-- ---------------------------------------------------------------------
CREATE TABLE saving (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint       NOT NULL,
    user_id         bigint,
    amount          numeric(38,2),
    balance         numeric(38,2),
    month           timestamp(6),
    channel         varchar(255),
    status          varchar(255),
    txn_id          varchar(255),
    created_at      timestamp(6),
    modified_at     timestamp(6),
    CONSTRAINT pk_saving              PRIMARY KEY (id),
    CONSTRAINT fk_saving_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_saving_user         FOREIGN KEY (user_id)         REFERENCES users (id)
);

-- ---------------------------------------------------------------------
-- Shares (tenant-owned). No modified_at column (matches the entity).
-- ---------------------------------------------------------------------
CREATE TABLE shares (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint       NOT NULL,
    user_id         bigint,
    amount          numeric(38,2),
    balance         numeric(38,2),
    account_details varchar(255),
    channel         varchar(255),
    remark          varchar(255),
    status          varchar(255),
    txn_id          varchar(255),
    type            varchar(255),
    created_at      timestamp(6),
    CONSTRAINT pk_shares              PRIMARY KEY (id),
    CONSTRAINT fk_shares_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_shares_user         FOREIGN KEY (user_id)         REFERENCES users (id)
);

-- ---------------------------------------------------------------------
-- Notifications (tenant-owned). reference_id is a generic reference
-- (matches the entity: not a mapped association -> no FK).
-- ---------------------------------------------------------------------
CREATE TABLE notification (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint       NOT NULL,
    recipient_id    bigint,
    sender_id       bigint,
    reference_id    bigint,
    is_read         boolean      NOT NULL,
    type            varchar(255),
    message         varchar(255),
    timestamp       timestamp(6),
    CONSTRAINT pk_notification              PRIMARY KEY (id),
    CONSTRAINT fk_notification_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_notification_recipient    FOREIGN KEY (recipient_id)    REFERENCES users (id),
    CONSTRAINT fk_notification_sender       FOREIGN KEY (sender_id)       REFERENCES users (id),
    CONSTRAINT ck_notification_type CHECK (type IN (
        'LOAN_APPROVED','LOAN_DECLINED','SHARES_APPROVED','SHARES_DECLINED',
        'GUARANTOR_REQUEST','GUARANTOR_APPROVED','GUARANTOR_DECLINED'))
);

-- =====================================================================
-- Indexes
-- =====================================================================

-- Tenant discriminator: one per tenant-owned table (drives every scoped query
-- and the Phase 2 @Filter). organizations (tenant root) and otp are excluded.
CREATE INDEX ix_users_organization_id        ON users        (organization_id);
CREATE INDEX ix_loan_organization_id         ON loan         (organization_id);
CREATE INDEX ix_repay_organization_id        ON repay        (organization_id);
CREATE INDEX ix_saving_organization_id       ON saving       (organization_id);
CREATE INDEX ix_shares_organization_id       ON shares       (organization_id);
CREATE INDEX ix_notification_organization_id ON notification (organization_id);

-- Per-tenant uniqueness on users.
--   * (organization_id, ledgerid) UNIQUE -- ledger IDs unique within an org.
--     ledgerid is nullable (unassigned during onboarding); Postgres treats NULLs
--     as distinct, so pre-assignment rows do not collide.
--   * (organization_id, psn) partial UNIQUE -- only where a PSN is actually present.
--   * (organization_id, email) NON-unique -- lookup performance only. Email
--     uniqueness is intentionally NOT DB-enforced in Phase 1.
CREATE UNIQUE INDEX ux_users_org_ledger ON users (organization_id, ledgerid);
CREATE UNIQUE INDEX ux_users_org_psn    ON users (organization_id, psn) WHERE psn IS NOT NULL AND psn <> '';
CREATE INDEX        ix_users_org_email  ON users (organization_id, email);

-- Association (foreign-key column) indexes -- PostgreSQL does not auto-index FK
-- columns; these back the tenant-scoped joins/lookups used across the app.
CREATE INDEX ix_loan_user_id              ON loan         (user_id);
CREATE INDEX ix_loan_guarantor1_id        ON loan         (guarantor1_id);
CREATE INDEX ix_loan_guarantor2_id        ON loan         (guarantor2_id);
CREATE INDEX ix_repay_user_id             ON repay        (user_id);
CREATE INDEX ix_repay_loan_id             ON repay        (loan_id);
CREATE INDEX ix_repay_parent_loan_id      ON repay        (parent_loan_id);
CREATE INDEX ix_saving_user_id            ON saving       (user_id);
CREATE INDEX ix_shares_user_id            ON shares       (user_id);
CREATE INDEX ix_notification_recipient_id ON notification (recipient_id);
CREATE INDEX ix_notification_sender_id    ON notification (sender_id);
CREATE INDEX ix_otp_email                 ON otp          (email);
