-- =====================================================================
-- COOPR8 Phase 4 / V3 -- Per-organization loan configuration and loan types.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   Loan rules are currently compiled into LoanServiceImpl: no interest,
--   exactly two guarantors, one active loan per type, a "real"+"material"
--   exclusion written as string literals, and no amount or tenure bounds at
--   all. Those are Citadel's rules wearing the platform's clothes. These two
--   tables move them to where a cooperative can own them.
--
--   organization_loan_config  -- exactly ONE row per organization
--   organization_loan_type    -- MANY rows per organization
--
-- NOTHING READS THESE TABLES YET
--   Stage 1 creates the schema, the entities and the repositories. No service
--   reads a value from here, so applying this migration changes no loan
--   decision and no member's money. The seeded defaults (V9) are deliberately
--   the values that reproduce today's behaviour, so that when Stage 2 wires
--   the reads in, no cooperative's rules move until an admin moves them.
--
-- INTEREST IS NEW FUNCTIONALITY, NOT A MIGRATION
--   There is no interest system to migrate. interest_method is seeded 'NONE'
--   and interest_rate 0.000, which is arithmetically identical to what
--   approveLoan does today (repay_amount = amount / duration).
--
--   The CHECK admits 'REDUCING_BALANCE' because the enum carries it -- the
--   schema should not need redesigning when reducing-balance support lands.
--   It is NOT selectable by an administrator: InterestMethod.adminSelectable
--   is false for it, and OrganizationConfigurationModelTest asserts that. A
--   value the engine cannot compute must not be reachable from a UI.
--                                                              [decision 1]
--
-- RATE BASIS IS FIXED, DELIBERATELY NOT CONFIGURABLE
--   interest_rate is an ANNUAL percentage. There is no rate_basis column, on
--   purpose: the same stored figure 12 means anything from 18,000 to 864,000
--   naira of interest depending on how it is read, so the basis is a platform
--   constant rather than a per-tenant setting.                 [decision 2]
--
-- NO EFFECTIVE DATING
--   A change here applies to loans approved AFTER it. Existing approved loans
--   are never recalculated -- they will carry their own applied terms (the
--   Class B columns, Stage 3). There is no valid_from column and no version
--   column, because there is no future-dated configuration.    [decision 4]
--
-- V1 AND V2 ARE NOT MODIFIED. Forward-only and purely additive: this file
-- creates two new tables and touches no existing row.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. organization_loan_config -- exactly one row per organization.
-- ---------------------------------------------------------------------
-- NULL means "no bound", not "zero". A NULL max_loan_amount is a cooperative
-- that has not set a ceiling; a 0 ceiling would forbid all borrowing. The
-- distinction is load-bearing, so none of the four bound columns is NOT NULL
-- and none is defaulted.
CREATE TABLE organization_loan_config (
    id                  bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id     bigint       NOT NULL,
    interest_method     varchar(32)  NOT NULL,
    interest_rate       numeric(6,3) NOT NULL,
    min_loan_amount     numeric(38,2),
    max_loan_amount     numeric(38,2),
    min_tenure_months   integer,
    max_tenure_months   integer,
    required_guarantors integer      NOT NULL,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    CONSTRAINT pk_organization_loan_config
        PRIMARY KEY (id),
    -- Cardinality is enforced, not assumed. Without this, a second row is a
    -- coin toss over which interest rate applies, and the bug surfaces months
    -- later as an intermittent rate. Hibernate `validate` does not check
    -- constraints, so OrganizationConfigConstraintTest asserts it too.
    CONSTRAINT uk_organization_loan_config_organization
        UNIQUE (organization_id),
    CONSTRAINT fk_organization_loan_config_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- Mirrors the InterestMethod enum. Adding a constant later requires
    -- altering this constraint -- Hibernate `validate` ignores CHECKs and
    -- will not warn, exactly as noted on V2's ck_otp_purpose.
    CONSTRAINT ck_organization_loan_config_interest_method
        CHECK (interest_method IN ('NONE', 'FLAT', 'REDUCING_BALANCE')),
    -- A negative rate would pay members to borrow.
    CONSTRAINT ck_organization_loan_config_interest_rate
        CHECK (interest_rate >= 0),
    -- Capped at 2 because Loan has exactly two guarantor columns and two
    -- guarantor status columns. Three would need a loan_guarantor child table
    -- and rework of the guarantor approval flow; a setting that silently caps
    -- at 2 while displaying 3 would be a lie told by the schema.
    CONSTRAINT ck_organization_loan_config_required_guarantors
        CHECK (required_guarantors BETWEEN 0 AND 2),
    CONSTRAINT ck_organization_loan_config_min_amount
        CHECK (min_loan_amount IS NULL OR min_loan_amount > 0),
    CONSTRAINT ck_organization_loan_config_max_amount
        CHECK (max_loan_amount IS NULL OR max_loan_amount > 0),
    CONSTRAINT ck_organization_loan_config_amount_window
        CHECK (min_loan_amount IS NULL
               OR max_loan_amount IS NULL
               OR min_loan_amount <= max_loan_amount),
    CONSTRAINT ck_organization_loan_config_min_tenure
        CHECK (min_tenure_months IS NULL OR min_tenure_months >= 1),
    CONSTRAINT ck_organization_loan_config_max_tenure
        CHECK (max_tenure_months IS NULL OR max_tenure_months >= 1),
    CONSTRAINT ck_organization_loan_config_tenure_window
        CHECK (min_tenure_months IS NULL
               OR max_tenure_months IS NULL
               OR min_tenure_months <= max_tenure_months)
);

-- The tenant discriminator is read on every configuration lookup. UNIQUE
-- above already provides an index on (organization_id), so a second plain
-- index would be redundant -- unlike the collection tables below, where the
-- unique key is composite and a lookup by organization alone still needs one.


-- ---------------------------------------------------------------------
-- 2. organization_loan_type -- many rows per organization.
-- ---------------------------------------------------------------------
-- Replaces the dead LoanType enum {real, soft, material}. Loan.type is
-- already a String, so historical values keep working untouched.
--
-- The per-type override columns are NULLABLE and mean "inherit from
-- organization_loan_config". NULL is the only honest encoding: 0.000 would
-- be an explicit interest-free product, which is a different statement.
CREATE TABLE organization_loan_type (
    id                  bigint        GENERATED BY DEFAULT AS IDENTITY,
    organization_id     bigint        NOT NULL,
    name                varchar(255)  NOT NULL,
    description         varchar(512),
    interest_method     varchar(32),
    interest_rate       numeric(6,3),
    min_loan_amount     numeric(38,2),
    max_loan_amount     numeric(38,2),
    min_tenure_months   integer,
    max_tenure_months   integer,
    max_active_loans    integer       NOT NULL,
    active              boolean       NOT NULL DEFAULT true,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    CONSTRAINT pk_organization_loan_type
        PRIMARY KEY (id),
    -- Redundant for uniqueness -- id is already the primary key -- but
    -- REQUIRED for referenceability: PostgreSQL will only accept a composite
    -- foreign key whose referenced column list carries its own unique
    -- constraint. Stage 3's loan.applied_loan_type_id depends on this, so
    -- that (organization_id, applied_loan_type_id) can be a real FK and the
    -- DATABASE refuses a cross-tenant loan type rather than the application
    -- being trusted never to write one.
    CONSTRAINT uk_organization_loan_type_org_id
        UNIQUE (organization_id, id),
    CONSTRAINT fk_organization_loan_type_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_organization_loan_type_interest_method
        CHECK (interest_method IS NULL
               OR interest_method IN ('NONE', 'FLAT', 'REDUCING_BALANCE')),
    CONSTRAINT ck_organization_loan_type_interest_rate
        CHECK (interest_rate IS NULL OR interest_rate >= 0),
    CONSTRAINT ck_organization_loan_type_name
        CHECK (btrim(name) <> ''),
    -- 1 reproduces today's hardcoded "one active loan per type" rule.
    CONSTRAINT ck_organization_loan_type_max_active_loans
        CHECK (max_active_loans >= 1),
    CONSTRAINT ck_organization_loan_type_min_amount
        CHECK (min_loan_amount IS NULL OR min_loan_amount > 0),
    CONSTRAINT ck_organization_loan_type_max_amount
        CHECK (max_loan_amount IS NULL OR max_loan_amount > 0),
    CONSTRAINT ck_organization_loan_type_amount_window
        CHECK (min_loan_amount IS NULL
               OR max_loan_amount IS NULL
               OR min_loan_amount <= max_loan_amount),
    CONSTRAINT ck_organization_loan_type_min_tenure
        CHECK (min_tenure_months IS NULL OR min_tenure_months >= 1),
    CONSTRAINT ck_organization_loan_type_max_tenure
        CHECK (max_tenure_months IS NULL OR max_tenure_months >= 1),
    CONSTRAINT ck_organization_loan_type_tenure_window
        CHECK (min_tenure_months IS NULL
               OR max_tenure_months IS NULL
               OR min_tenure_months <= max_tenure_months)
);

CREATE INDEX ix_organization_loan_type_organization_id
    ON organization_loan_type (organization_id);

-- One product name per cooperative, case-insensitively: "Soft" and "soft"
-- are the same product to a member reading an application form, and
-- Loan.type stores the name as text. Scoped to the organization, never
-- global -- two cooperatives may both offer a "Soft Loan".
CREATE UNIQUE INDEX ux_organization_loan_type_org_name
    ON organization_loan_type (organization_id, lower(btrim(name)));

-- A loan type is NEVER hard-deleted: a type referenced by a historical loan
-- cannot be removed without orphaning that loan's terms. "Delete" in the
-- admin UI means active = false, which removes the product from the
-- application form and leaves it in history. This index serves the
-- application-form read (active types for this tenant).
CREATE INDEX ix_organization_loan_type_org_active
    ON organization_loan_type (organization_id, active);
