-- =====================================================================
-- COOPR8 Phase 4 / V4 -- Per-organization savings plans.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   Savings plans exist today as three bare numbers on each member record:
--   users.saving_plan, users.special_saving_plan, users.share_plan. A number
--   on a member row cannot say what the plan is called, what it costs, or
--   whether the cooperative still offers it. This table gives a cooperative
--   named plans it owns.
--
-- MEMBER PLAN DATA IS NOT REWRITTEN
--   The three numeric columns on `users` are NOT dropped, renamed, migrated
--   or read by this file. Rewriting member plan data is a production data
--   change and is not a migration's decision. A nullable plan reference on
--   `saving` comes later (Stage 3, Class B), and even then the numbers stay.
--
-- NOTHING READS THIS TABLE YET
--   Stage 1 is schema + entities + repositories only. No service reads a
--   plan, so applying this changes no member's contributions.
--
-- FREQUENCY IS DESCRIPTIVE, NOT A SCHEDULER
--   `frequency` labels the plan ("monthly") and will be snapshotted onto a
--   savings posting in Stage 3. NOTHING enforces contribution timing: there
--   is no due-date engine, no arrears calculation and no dunning in COOPR8,
--   and this migration does not pretend otherwise. It is recorded because a
--   plan amount without a period is meaningless to a member reading it --
--   "5,000" is not a plan, "5,000 monthly" is.
--
-- V1, V2 AND V3 ARE NOT MODIFIED. Purely additive: one new table.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. organization_savings_plan -- many rows per organization.
-- ---------------------------------------------------------------------
-- plan_amount is the plan's own contribution figure and is NOT NULL: a plan
-- without an amount is not a plan. min_amount/max_amount are the OPTIONAL
-- bounds on what a member may actually post against it, and NULL there means
-- "no bound" -- the same NULL-is-not-zero rule as V3.
CREATE TABLE organization_savings_plan (
    id                bigint        GENERATED BY DEFAULT AS IDENTITY,
    organization_id   bigint        NOT NULL,
    name              varchar(255)  NOT NULL,
    description       varchar(512),
    plan_amount       numeric(38,2) NOT NULL,
    frequency         varchar(32)   NOT NULL,
    min_amount        numeric(38,2),
    max_amount        numeric(38,2),
    active            boolean       NOT NULL DEFAULT true,
    created_at        timestamp(6),
    updated_at        timestamp(6),
    CONSTRAINT pk_organization_savings_plan
        PRIMARY KEY (id),
    -- Redundant for uniqueness, REQUIRED for referenceability: Stage 3's
    -- saving.applied_savings_plan_id becomes a composite FK on
    -- (organization_id, applied_savings_plan_id), which PostgreSQL only
    -- accepts against a unique constraint on exactly those columns. Same
    -- reasoning as uk_organization_loan_type_org_id in V3.
    CONSTRAINT uk_organization_savings_plan_org_id
        UNIQUE (organization_id, id),
    CONSTRAINT fk_organization_savings_plan_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- Mirrors the SavingsFrequency enum; `validate` ignores CHECKs, so
    -- adding a constant means altering this constraint deliberately.
    CONSTRAINT ck_organization_savings_plan_frequency
        CHECK (frequency IN ('WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY')),
    CONSTRAINT ck_organization_savings_plan_name
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_organization_savings_plan_plan_amount
        CHECK (plan_amount > 0),
    CONSTRAINT ck_organization_savings_plan_min_amount
        CHECK (min_amount IS NULL OR min_amount > 0),
    CONSTRAINT ck_organization_savings_plan_max_amount
        CHECK (max_amount IS NULL OR max_amount > 0),
    CONSTRAINT ck_organization_savings_plan_amount_window
        CHECK (min_amount IS NULL
               OR max_amount IS NULL
               OR min_amount <= max_amount)
);

CREATE INDEX ix_organization_savings_plan_organization_id
    ON organization_savings_plan (organization_id);

-- One plan name per cooperative, case-insensitively. Scoped to the tenant:
-- two cooperatives may both run a "Special Savings".
CREATE UNIQUE INDEX ux_organization_savings_plan_org_name
    ON organization_savings_plan (organization_id, lower(btrim(name)));

-- A plan a member has contributed under is NEVER hard-deleted; "delete"
-- means active = false. This serves the enrolment-form read.
CREATE INDEX ix_organization_savings_plan_org_active
    ON organization_savings_plan (organization_id, active);
