-- =====================================================================
-- COOPR8 Phase 4 / V5 -- Per-organization shares configuration.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   SharesServiceImpl hardcodes: approval is always required, a purchase
--   must be > 0, a withdrawal must be > 0 and <= balance. There is no share
--   price and no unit concept at all -- `shares` holds a naira amount and
--   nothing else, so "how many shares does this member hold" is currently
--   unanswerable. This table gives a cooperative both.
--
-- SHARE PRICE 1.00 IS THE BEHAVIOUR-PRESERVING SEED, NOT A DEFAULT PRICE
--   With share_price = 1.00, units == naira, which is exactly the arithmetic
--   the platform performs today. It is seeded that way in V9 so that Phase 4
--   shipping does not silently reprice anybody's holding. A cooperative that
--   wants a real share price sets one deliberately, and only postings made
--   AFTER that change use it -- existing shares rows are never repriced.
--                                                              [decision 4]
--
-- NOTHING READS THIS TABLE YET, and no `shares` row is touched by this file.
--
-- V1-V4 ARE NOT MODIFIED. Purely additive: one new table.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. organization_shares_config -- exactly one row per organization.
-- ---------------------------------------------------------------------
CREATE TABLE organization_shares_config (
    id                    bigint        GENERATED BY DEFAULT AS IDENTITY,
    organization_id       bigint        NOT NULL,
    share_price           numeric(38,2) NOT NULL,
    min_purchase_amount   numeric(38,2),
    max_purchase_amount   numeric(38,2),
    approval_required     boolean       NOT NULL,
    withdrawal_allowed    boolean       NOT NULL,
    min_withdrawal_amount numeric(38,2),
    created_at            timestamp(6),
    updated_at            timestamp(6),
    CONSTRAINT pk_organization_shares_config
        PRIMARY KEY (id),
    -- Exactly one. Two rows would be two share prices, and the one that won
    -- would depend on row order.
    CONSTRAINT uk_organization_shares_config_organization
        UNIQUE (organization_id),
    CONSTRAINT fk_organization_shares_config_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- Strictly positive: a zero price makes units = amount / 0, and a
    -- negative one is not a share.
    CONSTRAINT ck_organization_shares_config_share_price
        CHECK (share_price > 0),
    CONSTRAINT ck_organization_shares_config_min_purchase
        CHECK (min_purchase_amount IS NULL OR min_purchase_amount > 0),
    CONSTRAINT ck_organization_shares_config_max_purchase
        CHECK (max_purchase_amount IS NULL OR max_purchase_amount > 0),
    CONSTRAINT ck_organization_shares_config_purchase_window
        CHECK (min_purchase_amount IS NULL
               OR max_purchase_amount IS NULL
               OR min_purchase_amount <= max_purchase_amount),
    CONSTRAINT ck_organization_shares_config_min_withdrawal
        CHECK (min_withdrawal_amount IS NULL OR min_withdrawal_amount > 0)
);
