-- =====================================================================
-- COOPR8 Phase 4 / V6 -- Per-organization repayment configuration.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   RepayServiceImpl requires a repayment to be an EXACT MULTIPLE of the
--   scheduled instalment. That rule makes some loans unpayable: 100,000 over
--   3 months gives an instalment of 33,333.33, three of which are 99,999.99,
--   so the final kobo can never be paid and the loan never closes. This table
--   lets a cooperative decide whether partial payment is allowed and what
--   rounding tolerance counts as settled.
--
-- PENALTIES ARE DELIBERATELY ABSENT
--   The Phase 4 architecture listed penalty rules under this domain. They are
--   NOT here, by decision: penalties are deferred to a future phase, and a
--   penalty column that no code charges is worse than no column at all. An
--   administrator who sees "Late penalty: 5%" in a settings screen will
--   reasonably believe late members are being charged 5%. Nothing in COOPR8
--   would charge it. So there is no penalty_rate, no grace_period_days and no
--   penalty_method in this schema.                             [decision 6]
--
-- NOTHING READS THIS TABLE YET
--   The exact-multiple rule in RepayServiceImpl is UNCHANGED by this file and
--   still applies. Replacing it is Stage 2 work; the 100,000-over-3-months
--   defect is still present in the code after this migration.
--
-- V1-V5 ARE NOT MODIFIED. Purely additive: one new table.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. organization_repayment_config -- exactly one row per organization.
-- ---------------------------------------------------------------------
-- All three behavioural flags are NOT NULL with no DEFAULT. A repayment rule
-- that is NULL is a repayment rule nobody chose, and the code reading it
-- would need a hardcoded fallback -- which is the exact thing Phase 4 exists
-- to remove. V9 seeds every existing organization explicitly.
CREATE TABLE organization_repayment_config (
    id                      bigint        GENERATED BY DEFAULT AS IDENTITY,
    organization_id         bigint        NOT NULL,
    allow_partial_repayment boolean       NOT NULL,
    allow_overpayment       boolean       NOT NULL,
    settlement_tolerance    numeric(38,2) NOT NULL,
    created_at              timestamp(6),
    updated_at              timestamp(6),
    CONSTRAINT pk_organization_repayment_config
        PRIMARY KEY (id),
    CONSTRAINT uk_organization_repayment_config_organization
        UNIQUE (organization_id),
    CONSTRAINT fk_organization_repayment_config_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- The residual a cooperative is willing to write off to call a loan
    -- settled. 0.00 means "must be paid to the kobo", which is today's
    -- behaviour and the seeded value. Capped at 1.00 naira: a tolerance
    -- larger than that is not rounding, it is forgiving debt, and forgiving
    -- debt is a deliberate transaction with an audit trail, not a setting.
    CONSTRAINT ck_organization_repayment_config_tolerance
        CHECK (settlement_tolerance >= 0 AND settlement_tolerance <= 1.00)
);
