-- =====================================================================
-- COOPR8 Phase 4 / V7 -- Per-organization membership / onboarding configuration.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   Which fields a signup must supply is currently fixed in bean validation
--   on UserRequest (@NotBlank on firstName, lastName, gender, email, phone,
--   address; nothing on psn or passport), and a self-service signup always
--   lands as status 'PENDING' awaiting admin activation. Different
--   cooperatives collect different things. This table lets them say so.
--
-- WHAT IS DELIBERATELY NOT HERE: SECURITY CONTROLS
--   No password_regex. No password_min_length. No token lifetime. No OTP
--   length or expiry. No session or JWT setting of any kind.
--
--   This is the single most important omission in Phase 4 and it is not an
--   oversight. A tenant-editable password rule is a tenant-editable security
--   control: an organization admin who sets the regex to '.*' has disabled
--   password strength for every member of that cooperative, from a settings
--   screen, with no platform review. The same reasoning covers token
--   lifetimes and one-time-code expiry. These are platform constants, owned
--   by the platform, and OrganizationConfigurationModelTest asserts that no
--   field matching those names exists on ANY of the seven configuration
--   entities -- so a future well-meaning migration that adds one fails the
--   build.
--
--   The two fields below that DO look security-adjacent are not:
--     - require_* are data-completeness rules, not authentication rules.
--     - auto_activate_members decides whether a new member waits for a human,
--       which is a membership policy every cooperative genuinely owns. It
--       cannot grant a role: role assignment is fixed in UserServiceImpl and
--       UserRequest has no role field to carry one.
--
-- NOTHING READS THIS TABLE YET. UserRequest validation is unchanged.
--
-- V1-V6 ARE NOT MODIFIED. Purely additive: one new table.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. organization_membership_config -- exactly one row per organization.
-- ---------------------------------------------------------------------
CREATE TABLE organization_membership_config (
    id                    bigint       GENERATED BY DEFAULT AS IDENTITY,
    organization_id       bigint       NOT NULL,
    require_email         boolean      NOT NULL,
    require_phone         boolean      NOT NULL,
    require_psn           boolean      NOT NULL,
    require_passport      boolean      NOT NULL,
    require_next_of_kin   boolean      NOT NULL,
    auto_activate_members boolean      NOT NULL,
    default_member_status varchar(32)  NOT NULL,
    created_at            timestamp(6),
    updated_at            timestamp(6),
    CONSTRAINT pk_organization_membership_config
        PRIMARY KEY (id),
    CONSTRAINT uk_organization_membership_config_organization
        UNIQUE (organization_id),
    CONSTRAINT fk_organization_membership_config_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- The status a newly created member starts in. Constrained to the values
    -- refuseByStatus() in UserServiceImpl actually understands: a cooperative
    -- that could type a free-form status here would create members whose
    -- accounts no code path can ever unlock. 'ACTIVE' is only reachable in
    -- combination with auto_activate_members, enforced below.
    CONSTRAINT ck_organization_membership_config_status
        CHECK (default_member_status IN ('NEW', 'PENDING', 'ACTIVE')),
    -- The two settings cannot contradict each other. Auto-activation that
    -- lands a member in 'PENDING' would activate nobody; a default of
    -- 'ACTIVE' without auto-activation would bypass the approval step the
    -- cooperative said it wanted. Either the pair means "no human review"
    -- or it does not.
    CONSTRAINT ck_organization_membership_config_activation
        CHECK ((auto_activate_members = true  AND default_member_status = 'ACTIVE')
            OR (auto_activate_members = false AND default_member_status <> 'ACTIVE'))
);
