-- =====================================================================
-- COOPR8 Phase 4 / V8 -- Configuration audit, append-only.
-- =====================================================================
--
-- WHAT THIS MIGRATION IS FOR
--   A configuration change that commits without a record of who made it is
--   an unexplained interest-rate change in a system that lends people money.
--   This table records every one: who, which domain, which field, from what,
--   to what, when, and why.
--
-- APPEND-ONLY IS ENFORCED, NOT INTENDED
--   Four layers, of which this migration is the last and the only one that
--   survives a developer who never reads any of this:
--     1. The entity has no setters and every @Column is updatable = false.
--     2. The repository declares no delete* method and no mutating path.
--     3. An ArchUnit rule stops any class outside the audit writer reaching
--        the repository (Stage 2, when the writer exists).
--     4. The database trigger below, which refuses UPDATE and DELETE.
--
--   TRUNCATE IS NOT BLOCKED, and that is a deliberate boundary rather than an
--   omission. TRUNCATE requires ownership of the table, which an application
--   role has no reason to hold in production; UPDATE and DELETE need only the
--   ordinary privileges the application already has, so those are the two an
--   application bug or a careless fix could actually perform. The integration
--   test harness also truncates every tenant table between tests, and a
--   trigger the test suite has to disable is a documented way to disable the
--   guard -- worse than not having it. This trigger defends against the
--   application, not against a database owner.
--
-- WHY old_value / new_value ARE text
--   This table spans seven domains whose values are numerics, booleans, enums
--   and strings. text is correct here for the one reason it is usually wrong
--   elsewhere: nothing reads these columns to make a decision. It is a record
--   OF values, not a source of them.
--
-- NO CLASS C VALUE CAN REACH THIS TABLE
--   No password rule, token lifetime or secret is representable in Phase 4
--   configuration at all (see V7), so none can be written here. The audit
--   cannot leak a secret it has no way to be given.
--
-- effective_date UNDER IMMEDIATE-EFFECT CONFIGURATION
--   Configuration takes effect immediately, so effective_date always equals
--   the date the change was recorded. The column is kept because it is a
--   record of when the terms began applying, and because reporting should not
--   have to infer that from created_at if future-dated configuration is ever
--   introduced. It is NOT a control: no code will read it to decide which
--   configuration is live.                                     [decision 4]
--
-- V1-V7 ARE NOT MODIFIED. This file creates one table, one function, one
-- trigger, and adds one unique constraint to `users` (additive, cannot fail).
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. users -- referenceable by (organization_id, id).
-- ---------------------------------------------------------------------
-- Needed so the audit row below can carry a COMPOSITE foreign key to its
-- actor. Without it the audit could only reference users(id), and "the admin
-- who changed this cooperative's interest rate is a member of a DIFFERENT
-- cooperative" would be a row the database happily accepts.
--
-- Redundant for uniqueness -- id is already the primary key -- and therefore
-- incapable of failing against existing data, whatever it contains. It exists
-- purely to make the column pair referenceable.
ALTER TABLE users
    ADD CONSTRAINT uk_users_org_id UNIQUE (organization_id, id);


-- ---------------------------------------------------------------------
-- 2. organization_config_audit -- many rows per organization, append-only.
-- ---------------------------------------------------------------------
CREATE TABLE organization_config_audit (
    id               bigint        GENERATED BY DEFAULT AS IDENTITY,
    organization_id  bigint        NOT NULL,
    actor_user_id    bigint        NOT NULL,
    actor_ledger_id  varchar(255),
    config_domain    varchar(64)   NOT NULL,
    setting_key      varchar(128)  NOT NULL,
    old_value        text,
    new_value        text,
    effective_date   date          NOT NULL,
    reason           varchar(512),
    created_at       timestamp(6)  NOT NULL,
    CONSTRAINT pk_organization_config_audit
        PRIMARY KEY (id),
    -- Redundant for uniqueness, REQUIRED for referenceability: Stage 3's
    -- loan.terms_config_audit_id becomes a composite FK on
    -- (organization_id, terms_config_audit_id), so a loan cannot cite another
    -- cooperative's configuration change as the origin of its terms.
    CONSTRAINT uk_organization_config_audit_org_id
        UNIQUE (organization_id, id),
    CONSTRAINT fk_organization_config_audit_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- COMPOSITE, not a bare actor_user_id: the actor must belong to the
    -- cooperative whose configuration changed, and the database enforces it.
    CONSTRAINT fk_organization_config_audit_actor
        FOREIGN KEY (organization_id, actor_user_id)
        REFERENCES users (organization_id, id),
    -- The seven configurable domains. The audit itself is the eighth Phase 4
    -- table and is absent on purpose: it never audits itself.
    --
    -- LOAN_TYPE_EXCLUSION is a domain of its own rather than part of
    -- LOAN_TYPE: an exclusion is a rule about a PAIR of types, so a change to
    -- it cannot be attributed to either one of them without the record being
    -- misleading about what was altered. It is listed here rather than added
    -- by a follow-up migration because this file has never been applied to any
    -- database (see docs §9.1) -- and an ALTER that only exists to correct an
    -- unapplied CHECK is history that never happened.
    CONSTRAINT ck_organization_config_audit_domain
        CHECK (config_domain IN ('LOAN_CONFIG',
                                 'LOAN_TYPE',
                                 'LOAN_TYPE_EXCLUSION',
                                 'SAVINGS_PLAN',
                                 'SHARES_CONFIG',
                                 'REPAYMENT_CONFIG',
                                 'MEMBERSHIP_CONFIG')),
    CONSTRAINT ck_organization_config_audit_setting_key
        CHECK (btrim(setting_key) <> ''),
    -- old_value IS NULL is meaningful (a first-ever set) so it is not
    -- constrained. new_value NULL is meaningful too (a bound being cleared).
    -- What is NOT meaningful is a row that records no change at all.
    CONSTRAINT ck_organization_config_audit_change
        CHECK (old_value IS DISTINCT FROM new_value)
);

-- The tenant discriminator. UNIQUE (organization_id, id) above is
-- organization-leading, so it already serves a lookup by organization alone;
-- this index exists for the ordered read below rather than for isolation.
CREATE INDEX ix_organization_config_audit_organization_id
    ON organization_config_audit (organization_id);

-- The read this table is actually for: "show me this cooperative's changes to
-- its loan configuration, newest first."
CREATE INDEX ix_organization_config_audit_org_domain_created
    ON organization_config_audit (organization_id, config_domain, created_at DESC);


-- ---------------------------------------------------------------------
-- 3. The append-only trigger.
-- ---------------------------------------------------------------------
-- One function serves both events. TG_OP is reported in the message so the
-- failure names what was attempted rather than leaving a developer guessing
-- which statement the database refused.
CREATE FUNCTION coopr8_config_audit_is_append_only() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION
        'organization_config_audit is append-only: % is not permitted on this table.',
        TG_OP
        USING HINT = 'A configuration audit record is evidence of a financial rule change. '
                     'Correct a mistaken change by making the corrective change, which writes '
                     'its own audit row -- never by editing or removing the record of what '
                     'happened. If a row is genuinely wrong, that is an incident to be '
                     'investigated, not a row to be tidied away.';
END $$;

CREATE TRIGGER tr_organization_config_audit_append_only
    BEFORE UPDATE OR DELETE ON organization_config_audit
    FOR EACH ROW
    EXECUTE FUNCTION coopr8_config_audit_is_append_only();
